[project]
name = "thinky-manifolds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jax[tpu]>=0.7.2",
    "optax>=0.2.6",
    "pyright>=1.1.405",
    "pytest>=8.4.2",
    "treescope>=0.1.10",
]
