[project]
name = "thinky-manifolds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch>=2.8.0",
    "torchvision>=0.23.0",
    "wandb>=0.22.1",
]

[dependency-groups]
dev = []
